Add HUD Control Functionality
Whystedz/TheWhystedzGame pull request #100
Opened 2021-04-05 02:09 UTC by whuras

**!! All images and text are subject to change depending on who is creating the final UI images !!**

Text can be changed based on various states. See gif which changes the south button text depending on if they can Dig, drop a rope, or climb:
![leafyboi_rope](https://user-images.githubusercontent.com/46137966/113529596-d28a2f00-9591-11eb-8cdd-a262917a0b80.gif)

Sweeping Cooldown implemented for all four buttons (even though we might only need it for 1 or 2). Currently only implemented to monitor the combo cooldown from the ComboPlayer script.
![CD](https://user-images.githubusercontent.com/46137966/113529635-efbefd80-9591-11eb-8fb7-9a2ea3f37110.gif)

Currently exposed is the south button text for the different states, as well as the colour overlay depending on if the cooldown is active (ie, dark grey for on cooldown).
![image](https://user-images.githubusercontent.com/46137966/113529670-06fdeb00-9592-11eb-81e3-76380cb60079.png)

2021-04-05 04:33 UTC, danielwiktorczyk commented
> **!! All images and text are subject to change depending on who is creating the final UI images !!**
> 
> Text can be changed based on various states. See gif which changes the south button text depending on if they can Dig, drop a rope, or climb:
> ![leafyboi_rope](https://user-images.githubusercontent.com/46137966/113529596-d28a2f00-9591-11eb-8cdd-a262917a0b80.gif)
> 
> Sweeping Cooldown implemented for all four buttons (even though we might only need it for 1 or 2). Currently only implemented to monitor the combo cooldown from the ComboPlayer script.
> ![CD](https://user-images.githubusercontent.com/46137966/113529635-efbefd80-9591-11eb-8fb7-9a2ea3f37110.gif)
> 
> Currently exposed is the south button text for the different states, as well as the colour overlay depending on if the cooldown is active (ie, dark grey for on cooldown).
> ![image](https://user-images.githubusercontent.com/46137966/113529670-06fdeb00-9592-11eb-81e3-76380cb60079.png)

Can you make the combo button one of the bottom / right ones? Usually the left and top buttons are not the ones used too often

2021-04-05 04:36 UTC, danielwiktorczyk commented
![image](https://user-images.githubusercontent.com/24488852/113537483-dd02f380-95a6-11eb-9f87-d3372c6441b3.png)

I would expect this to be a different state: Remove Rope (or similar). Dig is not the right state

2021-04-05 04:40 UTC, danielwiktorczyk commented
@whuras could you implement the proper combo button binding in this PR please? With keyboard, the spacebar (dig) button also triggers the combo, so it's still overloaded.

2021-04-05 04:42 UTC, danielwiktorczyk commented
![image](https://user-images.githubusercontent.com/24488852/113537821-b42f2e00-95a7-11eb-8923-9af3dca1a5cd.png)
In this case, the cool down should be on the combo button, because I have just Combod

2021-04-05 04:44 UTC, danielwiktorczyk commented
Not to get too into the art side of things, but can you change the white text to grey if the option is not available? 

For example, if I am unable to do a combo (cooldown, lack of nearby teammates), then both the ui icon and text should be greyed out. Ofc, the UI art will be replaced, but having the functionality of it greying out, or being in a "UI-disabled" state, I think, would be most useful if done now

2021-04-05 04:49 UTC, danielwiktorczyk requested changes
Loving the UI! And the cooldowns!!! I posted a bunch of comments in the main thread, if you have time. Thanks!

2021-04-05 04:49 UTC, danielwiktorczyk commented on Assets/Scripts/HUDButtonCooldown.cs
> +        imageNormal = GetComponent<Image>();
check your `this`

2021-04-05 04:49 UTC, danielwiktorczyk commented on Assets/Scripts/HUDMainButtons.cs
> +    public GameObject northButton;
hmmm maybe instead of directions, you can name them after the available options: 
`dance, combo, microphone, tileInteration`

2021-04-05 16:53 UTC, eli-lam approved these changes
LGTM!

2021-04-05 19:25 UTC, shifatkhan approved these changes
Works on Xbox One controller 👍

2021-04-05 22:23 UTC, whuras commented on Assets/Scripts/HUDMainButtons.cs
> +    public GameObject northButton;
Since we're still (as of your above comments) moving the buttons around, and we haven't received feedback from playtesting to even see which buttons are most intuitive I think it's a safer option to keep them identified by directions. If we decide to again change the order, then I'll have to go in and change the code in multiple places. This way we can change the order simply by changing the text - the artists can even do this and not have to worry about the coding at all.

2021-04-06 18:38 UTC, danielwiktorczyk approved these changes
Nice UX!

2021-04-06 19:41 UTC, merged