Player movement and camera controls
Whystedz/TheWhystedzGame pull request #15
Opened 2021-03-01 23:22 UTC by whuras

2021-03-04 00:42 UTC, shifatkhan reviewed
Camera rotation is affected by mouse movement, is that the intended functionality?
I though we were going for a camera that rotates based on character movement only

2021-03-04 15:34 UTC, whuras commented
> Camera rotation is affected by mouse movement, is that the intended functionality?
> I though we were going for a camera that rotates based on character movement only

Rotation is affected by the mouse OR right joystick on the controller. We haven't 100% decided if we're allowing manual manipulation of the camera. Right now it's coded to allow it while we're testing/prototyping for the first iteration of the 3Cs. There are two movement types included in the PR:
1. Player movement (WASD/left joystick) is completely independent of the camera movement (mouse/right joystick), and
2. Player movement is relative to the camera direction (ie, W/forward moves forward relative to the forward direction of the camera.
Both these methods have manual camera movement.

2021-03-04 19:38 UTC, shifatkhan approved these changes

2021-03-04 22:54 UTC, eli-lam requested changes
All seems good, just leaving some comments to remind you of changes. I think we agreed that we won't be controlling the camera but the camera movement with the mouse has inverted axes and it's tripping me up.

2021-03-04 22:54 UTC, eli-lam commented on Assets/Scripts/PlayerMovement.cs
> +        InputManager = InputManager.Instance;
Giving me error. Change to `InputManager.GetInstance()`

2021-03-04 22:54 UTC, eli-lam commented on Assets/Scripts/PlayerMovement.cs
> +    private Vector3 CameraRight;
Change private variables to camelCase so that coding standards are followed

2021-03-04 23:10 UTC, zhengHugo commented on Assets/Scripts/PlayerMovement.cs
> +
Possibly add comment `// move player absolutely based on controller input`

2021-03-04 23:10 UTC, zhengHugo commented on Assets/Scripts/PlayerMovement.cs
> +    void MovePlayer2()
Possibly add comment `// move player based on camera direction `

2021-03-04 23:14 UTC, danielwiktorczyk commented on Assets/Scripts/PlayerMovement.cs
> +    void MovePlayer2()
Instead of adding a comment, you can put it in the method name itself.

Instead of `MovePlayer2`, try `MovePlayerBasedOnCameraDirection()`. `MovePlayer2` as a name lacks value as a developer reading the steps

2021-03-04 23:23 UTC, danielwiktorczyk requested changes
Not sure how useful "MovementState1" is in its current implementation, but it's a great start to the camera movement! Very smooth. 

In the future iterations, would love to see settings to adjust the pitch, depth, etc --- unless those are already available by Cinemachine? I'm not familiar with it yet. 

I'll try to get some Tiled ground, and we can work off this for now

Couple of comments, but otherwise looks good! 

Great work! 🎉

2021-03-04 23:23 UTC, danielwiktorczyk commented on Assets/Scripts/PlayerMovement.cs
> +    [SerializeField] [Range(1,2)]
Why is this a range? To me, it seems these steps should be discrete, and nonlinear. Having a slider in the IDE seems weird as opposed to a drop down that comes with an Enum

2021-03-04 23:23 UTC, danielwiktorczyk commented on Assets/Scripts/PlayerMovement.cs
> +    private int MovementState = 1;
This could be an enum instead, as mentioned. Allows for a description of the movementstate, rather than `1` or `2`

2021-03-07 01:59 UTC, whuras commented on Assets/Scripts/PlayerMovement.cs
> +        InputManager = InputManager.Instance;
done

2021-03-07 01:59 UTC, whuras commented on Assets/Scripts/PlayerMovement.cs
> +    private Vector3 CameraRight;
done

2021-03-07 01:59 UTC, whuras commented on Assets/Scripts/PlayerMovement.cs
> +        InputManager = InputManager.Instance;
done

2021-03-07 02:00 UTC, whuras commented on Assets/Scripts/PlayerMovement.cs
> +
Changing method name instead.

2021-03-07 02:00 UTC, whuras commented on Assets/Scripts/PlayerMovement.cs
> +    void MovePlayer2()
done

2021-03-07 16:29 UTC, danielwiktorczyk approved these changes

2021-03-08 20:05 UTC, eli-lam requested changes

2021-03-08 20:05 UTC, eli-lam commented on Assets/Scripts/InputManager.cs
> +    public static InputManager GetInstance() => instance;
`this.instance`

2021-03-08 20:05 UTC, eli-lam commented on Assets/Scripts/InputManager.cs
> +        if (instance != null && instance != this)
`this.instance`

2021-03-08 20:05 UTC, eli-lam commented on Assets/Scripts/InputManager.cs
> +            instance = this;
`this.instance`

2021-03-08 21:33 UTC, eli-lam approved these changes

2021-03-08 21:34 UTC, merged