Implement basic digging mechanic
Whystedz/TheWhystedzGame pull request #26
Opened 2021-03-13 01:39 UTC by zahranikbakht

Adds detection/highlight of the tile that will be dug, input for digging, falling through holes, etc.

2021-03-13 06:54 UTC, eli-lam requested changes
Works great, good job! Here's a few suggestions in addition to my comments so that we can keep it simple before we start changing gameplay parameters.

1. Reset the player's transform to normal scale, here's what worked for me
![image](https://user-images.githubusercontent.com/43484130/111022097-b7673d80-839e-11eb-855f-a3cfa600b5f3.png)
2. Make the player object a prefab
3. Change the digging key to spacebar. Using WASD to move and X to dig is a bit too hard rn because X is too close to WASD

2021-03-13 06:54 UTC, eli-lam commented on Assets/Scripts/Digging.cs
> +    private InputManager InputManager;
`camelCase`

2021-03-13 06:54 UTC, eli-lam commented on Assets/Scripts/Digging.cs
> +        if (this.GetComponent<PlayerMovement>().IsFalling())
Make `this.GetComponent<PlayerMovement>()` into a variable eg `PlayerMovementScript` or something and initialize it in awake. Getting it from the object it every update will lower performance

2021-03-13 06:54 UTC, eli-lam commented on Assets/Scripts/Digging.cs
> +        var layerMask = LayerMask.GetMask("TileMovementCollider");
Make this into a class variable, initialize in awake

2021-03-13 06:54 UTC, eli-lam commented on Assets/Scripts/PlayerMovement.cs
> +        var layerMask = LayerMask.GetMask("TileMovementCollider");
Make it a class variable, initialize in awake

2021-03-13 06:54 UTC, eli-lam commented on Assets/Scripts/PlayerMovement.cs
> +    public bool IsFalling() => this.isFalling;
What is this for?

2021-03-13 19:05 UTC, shifatkhan requested changes

2021-03-13 19:05 UTC, shifatkhan commented on Assets/Scripts/Digging.cs
> +    }
### Slight performance improvements
Instead of using `Debug.DrawLine`, you can use the Unity's [`OnDrawGizmos()`](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnDrawGizmos.html) function:
``` csharp
    private void OnDrawGizmos()
    {
        if (enableDebugMode)
        {
            Gizmos.color = Color.red;
            Gizmos.DrawLine(
                Vector3.right * 0.1f + transform.position,
                Vector3.right * 0.1f + transform.position + transform.forward * this.minDistanceToDiggableTile
            );

            Gizmos.color = Color.blue;
            Gizmos.DrawLine(
                transform.position,
                transform.position + transform.forward * this.maxDistanceToDiggableTile
            );
        }
    }
```

And then remove this line from the `Update()` function:
``` csharp
if (enableDebugMode)
            DrawDebugLines();
```

The reason we do this is because Debug has slight performance hit on the actual build (from what I've read).
You could make it so your Debug code only runs when you build your game with the ["Development Build" enabled](https://stackoverflow.com/a/42838394), but it's just better to use `OnDrawGizmos()` as stated above.

`OnDrawGizmos()` will also make it so we can see the Debug lines in the editor **without** running the game.

2021-03-13 19:05 UTC, shifatkhan commented on Assets/Scripts/Digging.cs
> +        }
A regular `for` loop has slightly better performance than a foreach (I recently learned this from Kyle, COMP476's TA):
``` csharp
int hitsLength = hits.Length;
for (int i = 0; i < hitsLength; i++)
    ...
```

We also initialize the Length as an int since C# doesn't optimize `for` loops like Java

2021-03-13 23:22 UTC, zhengHugo commented
The camera movement in Y-axis feels wired. I changed the Y-axis speed and the default height as follows and it feels better. 
![image](https://user-images.githubusercontent.com/37107000/111052388-5126fd00-8428-11eb-8d61-52252567eac3.png)
![image](https://user-images.githubusercontent.com/37107000/111052418-87fd1300-8428-11eb-817c-c440ca9dd87b.png)

2021-03-16 20:57 UTC, zhengHugo approved these changes

2021-03-17 03:19 UTC, eli-lam approved these changes
LGTM!

2021-03-17 03:56 UTC, merged