Feature/vivox #19
Whystedz/TheWhystedzGame pull request #51
Opened 2021-03-21 02:02 UTC by zhengHugo

Adding vivox core scripts.

To compile, you need to import vivox asset to your local environment:
1. Search for Vivox in Unity asset store, the one with a size of more than 300MB. 
2. Before clicking the import button, make sure to EXCLUDE the folder "Mirror" and "Sample", and "Test" is optional. 
3. Click import

2021-03-21 02:16 UTC, zhengHugo commented
For testing: 
1. Build VivoxScene under Yuguo's scene sandbox and run.
2. Login with an arbitrary username. 
3. Click "join channel"
4. Run another instance of the same scene, login and join channel with another username
5. You should be able to hear your own voice now.

2021-03-21 03:02 UTC, eli-lam commented
^ I suggest you to not include the Sample and Test folders in your import, they contain errors

2021-03-21 03:21 UTC, eli-lam commented
@zhengHugo I'm getting this error. Any way to fix? 
![image](https://user-images.githubusercontent.com/43484130/111892564-fe72b580-89d2-11eb-9496-6d104a7973bb.png)

2021-03-21 03:31 UTC, zhengHugo commented
> @zhengHugo I'm getting this error. Any way to fix?
> ![image](https://user-images.githubusercontent.com/43484130/111892564-fe72b580-89d2-11eb-9496-6d104a7973bb.png)

Can you try import Vivox again? It looks like you didn't import x86_64 package in the "Plugins" folder. 
Also, make sure to exclude "Mirror", "Sample", and "Test"

2021-03-21 04:08 UTC, eli-lam commented on .gitignore
>  /Assets/Vivox/
Can you change this to `/Assets/Vivox*`

2021-03-21 04:12 UTC, zhengHugo commented on .gitignore
>  /Assets/Vivox/
Done

2021-03-23 00:20 UTC, eli-lam approved these changes
Can you prefix all private members with `this.` when they are being called?

2021-03-23 00:21 UTC, zhengHugo commented
> > @zhengHugo I'm getting this error. Any way to fix?
> > ![image](https://user-images.githubusercontent.com/43484130/111892564-fe72b580-89d2-11eb-9496-6d104a7973bb.png)
> 
> Can you try to import Vivox again? It looks like you didn't import x86_64 package in the "Plugins" folder.
> Also, make sure to exclude "Mirror", "Sample", and "Test"

Solution to this:
1. In build settings, add the VivoxScene
2. Select the build platform based on your OS

2021-03-23 00:46 UTC, zhengHugo commented
> Can you prefix all private members with `this.` when they are being called?

Fixed.
Thank you for your review!

2021-03-23 03:07 UTC, shifatkhan requested changes
I can hear my own voice! 😱
Works perfectly fine, good stuff!

Can you just change the functions with 1 line of code into lambdas?
e.g. `private int Square(int x) => x*x;`

2021-03-23 03:12 UTC, shifatkhan requested changes

2021-03-23 03:12 UTC, shifatkhan commented on Assets/Scripts/Vivox/UI/TextChatUI.cs
> +    }
lamda:
```csharp
private void OnDestroy() => this.vivoxManager.OnTextMessageLogReceivedEvent -= OnTextMessageLogReceivedEvent;
```

2021-03-23 03:12 UTC, shifatkhan commented on Assets/Scripts/Vivox/VivoxManager.cs
> +        }
lamda:
```csharp
private void OnApplicationQuit() => this.client.Uninitialize();
```

2021-03-23 03:12 UTC, shifatkhan commented on Assets/Scripts/Vivox/VivoxManager.cs
> +        }
lamda:
```csharp
 public void LeaveChannel(IChannelSession channelSession) => channelSession.Disconnect();
 ```

2021-03-23 03:12 UTC, shifatkhan commented on Assets/Scripts/Vivox/VivoxManager.cs
> +        }
lamda:
```csharp
public void BtnLogin() => LogIn();
```

and 
```csharp
public void BtnJoinChannel() => JoinChannel(true, true, ChannelType.NonPositional);
```

2021-03-23 03:12 UTC, shifatkhan commented on Assets/Scripts/Vivox/VivoxManager.cs
> +}
Add a line break

2021-03-23 03:12 UTC, shifatkhan commented on Assets/Scripts/Vivox/UI/TextChatUI.cs
> +}
Add a line break

2021-03-24 02:01 UTC, zhengHugo commented on Assets/Scripts/Vivox/UI/TextChatUI.cs
> +}
Fixed. Thanks for your review.

2021-03-24 23:21 UTC, danielwiktorczyk approved these changes
Looks good! I know many of these files are boilerplate from Vivox themselves, so I won't make you refactor their code to suit our conventions, haha

2021-03-24 23:21 UTC, danielwiktorczyk commented on Assets/Scripts/Vivox/UI/TextChatUI.cs
> +
don't need this extra space

2021-03-24 23:21 UTC, danielwiktorczyk commented on Assets/Scripts/Vivox/UI/TextChatUI.cs
> +        {
can lose the brackets for this one liner

2021-03-24 23:38 UTC, shifatkhan approved these changes
Good stuff !

2021-03-25 00:55 UTC, merged