Combo Detection plus Team and Collectible Update
Whystedz/TheWhystedzGame pull request #65
Opened 2021-03-28 04:54 UTC by danielwiktorczyk

Does not include the actual digging part just yet

Try it out in my scene!

2021-03-28 19:22 UTC, eli-lam commented on Assets/Scripts/Tiling/Tile.cs
> +using Mirror.Cloud.Examples.Pong;
Why is this here?

2021-03-28 21:14 UTC, danielwiktorczyk commented on Assets/Scripts/Tiling/Tile.cs
> +using Mirror.Cloud.Examples.Pong;
Auto complete probably imported it haha. Will remove now

2021-03-29 02:32 UTC, zahranikbakht requested changes
Great job! I just found this error when I try to run my own scene on this branch. It just pops up once when I enable the player for the first time.
![errorimage](https://user-images.githubusercontent.com/60522280/112779663-34d4b400-9015-11eb-9590-fe71a0c858e2.png)

2021-03-29 02:34 UTC, zahranikbakht commented on Assets/Scripts/Combos/ComboPlayer.cs
> +    public bool IsInvolvedInACombo3;
I don't see these two variables being used anywhere. Ignore this if I'm blind lol

2021-03-29 03:54 UTC, danielwiktorczyk commented on Assets/Scripts/Combos/ComboPlayer.cs
> +    public bool IsInvolvedInACombo3;
Cleaned up!

2021-03-29 03:56 UTC, zahranikbakht approved these changes

2021-03-29 04:19 UTC, zhengHugo approved these changes

2021-03-29 04:26 UTC, merged