Implement Rope Mechanic
Whystedz/TheWhystedzGame pull request #67
Opened 2021-03-30 03:06 UTC by zahranikbakht

2021-03-31 00:25 UTC, danielwiktorczyk requested changes
>> will add more soon!

2021-03-31 02:26 UTC, danielwiktorczyk requested changes

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +            tile.isRopeIn = false;
This should be another state, not a boolean

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +
no space

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +
no space

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +    public IEnumerator RopeThrowing(GameObject ropeObject, Tile tile)
Name it ThrowRope (as an action)

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +            playerMovement.MoveTowards(ropeObject.transform.forward, 6f);
what's the 6f magic number?

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +        while (Vector3.Distance(this.transform.position, tileSurfacePosition) > 1.5f)
Hardcoded 1.5f, make it an adjustable value

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +    public bool MovementDisabled;
booleans with IsMovementDisabled

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +    [SerializeField] private Image img;
What's this for?

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +    public bool MovementDisabled;
or MovementIsDisabled

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +    public IEnumerator fadeIn()
PascalCase

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +        for (float i = 0; i <= 2; i += Time.deltaTime)
You can rename i to opacity

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +        for (float i = 0; i <= 2; i += Time.deltaTime)
Why 2?

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +    public IEnumerator fadeOut()
Pascal Case

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Player/Rope.cs
> +    private GameObject highlightLadder;
highlightedLadder

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Player/Rope.cs
> +    private bool inZone;
isInZone? not sure what this does just yet

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Player/Rope.cs
> +    private float heightToClimb = 8;
make this editable in inspector

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Player/Rope.cs
> +    public bool Saved;
IsSaved? 
You should create an enum for all the different states of the Rope, called RopeState

```
public enum RopeState {
   Normal, 
   ...
   }
   ```

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Tiling/Tile.cs
>      public IEnumerator HighlightTileForOneFrame()
I would leave this code here unchanged. Make a new method for highlighting it for the rope separately

Make sure my scene works for combos!!!

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +            if (tile.tileState == TileState.Normal)
combine this check in the prior boolean check. Too nested rn

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +            if (tile.tileState == TileState.Normal)
or refactor this method

2021-03-31 02:26 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +                playerMovement.MovementDisabled = !playerMovement.MovementDisabled;
woah why are we inverting it here? I think you want to do one or the other; either set them true, or false.

2021-03-31 03:13 UTC, eli-lam requested changes

2021-03-31 22:34 UTC, danielwiktorczyk commented on Assets/Scripts/Player/Rope.cs
> +        this.highlightLadder = this.transform.GetChild(2).gameObject;
true, this should be a drag and drop from the inspector if this is a prefab

2021-04-01 01:21 UTC, zahranikbakht commented on Assets/Scripts/Digging/Digging.cs
> +                playerMovement.MovementDisabled = !playerMovement.MovementDisabled;
You can throw/unthrow rope with the same button, so each button press results in inverting the movement freeze.

2021-04-01 01:30 UTC, zahranikbakht commented on Assets/Scripts/Player/Rope.cs
> +    private bool inZone;
checks if player is close enough to the ladder to highlight it.

2021-04-01 01:31 UTC, zahranikbakht commented on Assets/Scripts/Player/PlayerMovement.cs
> +    [SerializeField] private Image img;
it's just a plain black image used for fade in/fade out

2021-04-01 01:57 UTC, zahranikbakht commented on Assets/Scripts/Digging/Digging.cs
> +            playerMovement.MoveTowards(ropeObject.transform.forward, 6f);
it's just the speed that the character moves toward the rope when throwing one

2021-04-01 02:00 UTC, zahranikbakht commented on Assets/Scripts/Digging/Digging.cs
> +            playerMovement.MoveTowards(ropeObject.transform.forward, 6f);
made it adjustable tho it's not really important

2021-04-01 02:01 UTC, zahranikbakht commented on Assets/Scripts/Player/PlayerMovement.cs
> +        for (float i = 0; i <= 2; i += Time.deltaTime)
made the time adjustable

2021-04-01 03:21 UTC, zahranikbakht commented on Assets/Scripts/Tiling/Tile.cs
>      public IEnumerator HighlightTileForOneFrame()
I only added an extra condition for rope throwing. It works in your scene too.

2021-04-01 16:42 UTC, eli-lam commented on Assets/Scripts/Digging/Digging.cs
> +        {
Don't need the `{ }`

2021-04-01 16:42 UTC, eli-lam commented on Assets/Scripts/Digging/Digging.cs
> +            yield return 0;
Do `yield return null` instead, `yield return 0` allocates memory

2021-04-01 16:42 UTC, eli-lam commented on Assets/Scripts/Player/PlayerMovement.cs
>          {
Don't need the `{ }`

2021-04-01 16:42 UTC, eli-lam commented on Assets/Scripts/Player/Rope.cs
> +            yield return 0;
`yield return null`

2021-04-01 16:42 UTC, eli-lam commented on Assets/Scripts/Tiling/Tile.cs
> +            {
No need for `{ }`

2021-04-01 17:17 UTC, eli-lam approved these changes

2021-04-01 21:20 UTC, danielwiktorczyk requested changes
There are still some things I'd like to go over with you. Let's jump on a call!

2021-04-01 21:20 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +    public void InterctWithTile(Tile tile)
Interact (typo)

2021-04-01 21:20 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +    public void InterctWithTile(Tile tile)
Why is it called this anyway? This is pretty general. How are we interacting with it?

2021-04-01 21:20 UTC, danielwiktorczyk commented on Assets/Scripts/Digging/Digging.cs
> +        else if (rope.ropeState == RopeState.Normal && ((this.rope.gameObject.activeSelf && tile.tileState == TileState.RopeIn) || (!this.rope.gameObject.activeSelf && tile.tileState == TileState.Res
make this multiple lines. Currently, this compound condition is hard to follow

2021-04-01 21:20 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +        layerMask = LayerMask.GetMask("TileMovementCollider") | LayerMask.GetMask("Underground");
Rename this `layerMask`. The value you are setting it to is not a general one

2021-04-01 21:20 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +        if (closestCollider.gameObject.layer == LayerMask.NameToLayer("Underground"))
This doesn't seem like it will work all the time. 

It would be better to dynamically get the 1 normal plane, the 1 underground plane, and keep those references. Then, when you need to check this, you just do Vector3.Distance and find which one we're closest to. It's also overkill to do a collision check every frame for this!

2021-04-01 21:20 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +        while (this.transform.position.y < -70 + height)
the -70 is a magic number

2021-04-01 21:20 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
>          if (this.transform.position.y < -20)
this -20 is a magic number

2021-04-01 21:20 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +        this.transform.position = new Vector3(surfacePosition.x, surfacePosition.y+1f, surfacePosition.z);
Can do `this.transform.position += Vector3.up * 1f`
Also, that 1f is a magic number

2021-04-01 21:20 UTC, danielwiktorczyk commented on Assets/Scripts/Tiling/Tile.cs
> +        //StartCoroutine(PlayBreakingAnimation());
why are you removing this animation??

2021-04-01 21:20 UTC, danielwiktorczyk commented on Assets/Scripts/Tiling/Tile.cs
> +        this.gameObject.layer = LayerMask.NameToLayer("TileRope");
You shouldn't change the layer dynamically. Let's VC and I can help you with this

2021-04-01 21:20 UTC, danielwiktorczyk commented on Assets/Scripts/Tiling/Tile.cs
>      public IEnumerator HighlightTileForOneFrame()
But there are now multiple types of highlighting: simple dig, combo dig, and rope. We are adding too many conditions to this, and should instead make seperate methods that we call based on the context. E.g. HighlightWithRope, HighlightForCombo, HighlightForSimpleDig

2021-04-02 16:51 UTC, danielwiktorczyk approved these changes

2021-04-02 16:52 UTC, danielwiktorczyk commented
Excellent work!! Love the hole system. Merging-in-the-holeeeee!!

2021-04-02 16:53 UTC, merged