Add New Animations
Whystedz/TheWhystedzGame pull request #94
Opened 2021-04-03 00:44 UTC by whuras

![image](https://user-images.githubusercontent.com/46137966/113463534-2f4fe300-93f4-11eb-9f5b-f8bb75a5cfec.png)

2021-04-03 01:06 UTC, eli-lam requested changes
When the player respawns, the state is not changed back to IdleAboveGround

2021-04-03 06:50 UTC, eli-lam approved these changes

2021-04-03 18:49 UTC, danielwiktorczyk requested changes
A few requests regarding the code. Otherwise, I'm now gonna test it locally in my scene!

2021-04-03 18:49 UTC, danielwiktorczyk commented on Assets/Scripts/AnimationManager.cs
> +        if (Mathf.Abs(this.characterController.velocity.x) > 0 || Mathf.Abs(this.characterController.velocity.z) > 0)
Instead of this, try 

```
var isRunning = Mathf.Abs(this.characterController.velocity.x) > 0 || Mathf.Abs(this.characterController.velocity.z) > 0;
this.animator.SetBool("isRunning", isRunning);
```

2021-04-03 18:49 UTC, danielwiktorczyk commented on Assets/Scripts/AnimationManager.cs
> +            animator.SetBool("isClimbing", true);
More concisely, 
```
animator.SetBool("isClimbing", this.playerMovement.IsClimbing);
```

2021-04-03 18:49 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +        if(this.underground != null) CheckIfUnderground();
don't do this check. We need the playermovement to have `this.underground`. If it doesn't, let this error pop up, and it'll alert us accordingly. Otherwise, this is a silent suppression of the error, and can lead us into more bugs!

2021-04-03 18:49 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +        if (this.IsInUnderground)
if it's now public, lose the `this`

2021-04-03 18:49 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +        this.IsInUnderground = distanceToUnderground <= this.undergroundCheckThreshold;
lose this

2021-04-03 18:49 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
>          StartCoroutine(FadeIn());
an extra line to pad the logic would make it more readable

2021-04-03 18:49 UTC, danielwiktorczyk commented on Assets/Scripts/Player/PlayerMovement.cs
> +        IsClimbing = false;
an extra padding line before this set would make it more readable.

2021-04-03 18:49 UTC, danielwiktorczyk commented on Assets/Scripts/Underground.cs
> +        if (this.underground != null && this.transform.position.y <= this.underground.transform.position.y + undergroundOffset)
again, don't do this check

2021-04-03 18:56 UTC, danielwiktorczyk commented
@whuras currently the shooting animation is way too long. To dig a hole is instantaneous, but the animation takes a second or two. Maybe the animation should be reduced to 0.5s or so, whatever looks appropriate. Can you adjust this while you have this PR open please?

2021-04-04 00:30 UTC, danielwiktorczyk approved these changes
Great stuff!

2021-04-04 01:07 UTC, merged